org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=384m
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Project
mod_version=1.0.7+26.2
maven_group=dev.toolkitmc
archives_base_name=guiapi

# Minecraft / Fabric dependencies
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.152.2+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.0
