org.gradle.jvmargs=-Xmx1G -XX:MaxMetaspaceSize=384m
org.gradle.workers.max=1
org.gradle.daemon=false

# Project
mod_version=1.0.6+1.21.8
maven_group=dev.toolkitmc
archives_base_name=guiapi

# Minecraft / Fabric dependencies
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.2
fabric_version=0.136.1+1.21.8
modmenu_version=15.0.1
