name: Source Code (with Git History)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create source archive
        run: |
          mkdir archive
          sudo -i
          chmod +x archive/.git/objects/pack/*
          chmod +x archive/.git/objects/info/commit-graphs/commit-graph-chain
          
          rsync -a \
            --exclude archive \
            --exclude .github \
            ./ archive/

          cp -r .git archive/

      - name: Zip
        run: |
          zip -r source-with-history.zip archive

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-with-history
          path: source-with-history.zip
