name: Source Code (with Git History)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Create source archive
        run: |
          mkdir archive
          sudo -i
          chmod +x archive/.git/objects/pack/pack-ee2d1d33865e318313f743d82e7f44e0fb3b8db5.pac
          chnod +x archive/.git/objects/pack/pack-ee2d1d33865e318313f743d82e7f44e0fb3b8db5.idx
          chmod +x archive/.git/objects/pack/pack-ee2d1d33865e318313f743d82e7f44e0fb3b8db5.rev
          chmod +x archive/.git/objects/info/commit-graphs/commit-graph-chain
          chmod +x archive/.git/objects/info/commit-graphs/graph-365bd590154a4da12677540954e60b91a2be627d.graph
          
          rsync -a \
            --exclude archive \
            --exclude .github \
            ./ archive/

          cp -r .git archive/

      - name: Zip
        run: |
          zip -r source-with-history.zip archive

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: source-with-history
          path: source-with-history.zip
